### ISSUE TITLE
AttributeError on somd about combining rules

### ISSUE THREAD

**Issue by SofiaBariami** [michellab/Sire#257] opened 2019-03-14 09:54 UTC
Hi there! I have installed Sire with the implementation of the geometric combining rules on my computer. It was installed without any errors, however when I'm trying to run a free energy calculation with 
` ~/sire_combRules.app/bin/somd-freenrg -C ../../input/config.cfg -c ../../input/solvated.rst7 -t ../../input/solvated.parm7 -m ../../input/MORPH.pert -p CUDA -l 0.0 `
I get the following attribute error: 
``` 
### Running Single Topology Molecular Dynamics Free Energy on sce-chem-c01679.chem.ed.ac.uk ###
###================Setting up calculation=====================###
New run. Loading input and creating restart
lambda is 0.0
Create the System...
Selecting dummy groups
Creating force fields... 
Setting up the simulation with random seed 385781
Setting up moves...
Traceback (most recent call last):
  File "/home/sofia/sire_combRules.app/pkgs/sire-2019.1.0/share/Sire/scripts/somd-freenrg.py", line 146, in <module>
    OpenMMMD.runFreeNrg(params)
  File "/home/sofia/sire_combRules.app/lib/python3.7/site-packages/Sire/Tools/__init__.py", line 176, in inner
    retval = func()
  File "/home/sofia/sire_combRules.app/lib/python3.7/site-packages/Sire/Tools/OpenMMMD.py", line 1567, in runFreeNrg
    moves = setupMovesFreeEnergy(system, ranseed, gpu.val, lambda_val.val)
  File "/home/sofia/sire_combRules.app/lib/python3.7/site-packages/Sire/Tools/OpenMMMD.py", line 1143, in setupMovesFreeEnergy
    Integrator_OpenMM.setCombiningRules(combining_rules.val)
AttributeError: 'OpenMMFrEnergyST' object has no attribute 'setCombiningRules'
```
The thing is that 'setCombiningRules' is already defined in [openmmfrenergyst.h](https://github.com/michellab/Sire/blob/qube-combiningRules/corelib/src/libs/SireMove/openmmfrenergyst.h) and [OpenMMMD.py](https://github.com/michellab/Sire/blob/devel/wrapper/Tools/OpenMMMD.py) imports everything from SireMove. Isn't this enough or should I make more changes at OpenMMMD.py? 
I also checked the similar implementation of 'setCutoffType' and I can't find anything missing from my code for the combining rules. Any ideas/help would be very very much appreciated!

**Comment by lohedges** [comment] 2019-03-14 11:10
Hi Sofia,

This is likely because you haven't recreated the Python wrappers following the changes to the C++ code. Just do the following (this assumes that you are in the top level of the Sire repository):

```bash
cd wrapper
$HOME/sire.app/bin/python AutoGenerate/scanheaders.py $SIRE_SRC/corelib/src/libs . 
cd Move
$HOME/sire.app/bin/python ../AutoGenerate/create_wrappers.py
cd ../../
./compile_sire.sh
```

When you rebuild the wrappers you will see that several files in the `wrapper/Move` directory will have changed. To see you can run:

```bash
git status
```

You should then commit the files that have changed and push them to your branch. This will have to be done before the Qube pull request can be accepted. You should also add some tests to the SireUnitTest repository that makes sure that the new functionality is working.

**Comment by ppxasjsm** [comment] 2019-03-14 11:10
The issue is that it hasn't been exposed to the python layer. See what Lester said above..pretty much what I was going to say.

**Comment by lohedges** [comment] 2019-03-14 11:20
I forgot to mention that you might need to install some additional software to be able to compile the wrappers. You can read Christopher's instructions [here](https://github.com/michellab/Sire/blob/devel/wrapper/HOWTO_GENERATE_WRAPPERS). If you can't get things to work, I'm happy to check out your feature branch so I can rebuild the wrappers and upload the missing files for you.

Cheers.

**Comment by jmichel80** [comment] 2019-03-14 11:22
If you can't get things to work, I'm happy to check out your feature branch so I can rebuild the wrappers and upload the missing files for you.


Thanks Lester ! In the long run it’s better for Sofia to be comfortable with generating wrappers though.

Julien

**Comment by ppxasjsm** [comment] 2019-03-14 11:34
Or give me a shout and I'll come over and help with building the wrappers... then you know how to do it in the future.

**Comment by lohedges** [comment] 2019-03-14 11:36
Good plan @ppxasjsm, it would be good for @SofiaBariami to incorporate the wrapper building as part of the development process. This is another important reason for writing Python unit tests when there are API changes since you immediately realise that the wrappers haven't been updated.

**Comment by jmichel80** [comment] 2019-03-14 11:38
Bit surprised her unit test didn’t catch that.

**Comment by lohedges** [comment] 2019-04-09 12:49
Closing since we the missing wrappers have now been built. Might be good to think of a way of automatically rebuilding the wrappers if the API changes, or at least issuing a warning to the user when the re-run `compile_sire.sh`.

**Closed by lohedges** 2019-04-09 12:49 UTC
