### ISSUE TITLE
Issue calculating a range using analyse_freenerg

### ISSUE THREAD

**Issue by pharmlife** [michellab/Sire#224] opened 2018-08-29 13:26 UTC
I have performed waterswap calculations with 3000 iterations and am trying to understand how my results have converged. Per the guidance on analyse_freenrg, I have the following as my input - 

sire.app/bin/analyse_freenrg -i freenrgs.s3 -r 400 1000 -o results_1000.txt
sire.app/bin/analyse_freenrg -i freenrgs.s3 -r 400 2000 -o results_2000.txt
sire.app/bin/analyse_freenrg -i freenrgs.s3 -r 400 3000 -o results_3000.txt

However, for the first two calculations, I get the following error:

Traceback (most recent call last):
  File "/mnt/storage/scratch/hd16974/sire.app/pkgs/sire-2018.2.0/share/Sire/scripts/analyse_freenrg.py", line 413, in <module>
    "# %s = %s +/- %s kcal mol-1" % (result[0], result[2].deltaG(), result[2].values()[-1].yMaxError()))
IndexError: list index out of range

Apologies if I've missed something obvious, but can you shed any light as to why I'm seeing this error?

Thanks

**Comment by chryswoods** [comment] 2018-08-30 13:44
Hi,

I'm struggling to reproduce your error using my own waterswap freenrgs.s3 files, so suspect it may be something specific about your file. Could you email me the freenrgs.s3 file directly (christopher.woods@bristol.ac.uk). The file doesn't contain any information about the system you are simulating, so is safe to send if you are concerned about IP.

**Comment by chryswoods** [comment] 2019-01-31 16:12
Closing due to age. Please reopen if this is still an issue.

**Closed by chryswoods** 2019-01-31 16:12 UTC
