### ISSUE TITLE
AmberDihedral unable to expand series with negative k values.

### ISSUE THREAD

**Issue by lohedges** [michellab/Sire#192] opened 2018-02-13 18:57 UTC
It appears that the `AmberDihedral` object cannot expand series of the form `k [ 1 + cos (per Phi - phase) ]` when there are terms with negative values for `k`. For example, consider the following series (taken from an actual CHARMM dihedral function),

```
func = 0.3 [ 1 + cos Phi ]  - 0.3 [ 1 + cos (4 Phi) ],
```

which is expressed by the following by Sire

```
func = 0.3  cos Phi  - 0.3 cos (4 Phi) ].
```
Although this is a valid series, attempting to convert this to an `AmberDihedral` fails:

```python
from Sire.CAS import *
from Sire.MM import *

# Create the function expression.
func = Expression(0.3 * Cos(Symbol("Phi")) - 0.3 * Cos(4 * Symbol("Phi")))

# Attempt to create an AmberDihedral object.
amber_dihedral = AmberDihedral(func, Symbol("Phi"))
```

Now assume that the terms have the same sign for `k`, i.e.:

```
func = 0.3 [1 + cos Phi ] + 0.3 [1 + cos (4 Phi) ]
     = 0.6 + 0.3 cos Phi + 0.3 cos (4 Phi)
```
(I know this can be simplified further, I'm just expressing it in the same way as Sire.)

The following works fine:

```python
func = Expression(0.6 + 0.3 * Cos(Symbol("Phi")) + 0.3 * Cos(4 * Symbol("Phi")))
amber_dihedral = AmberDihedral(func, Symbol("Phi"))
```
It seems that any negative `k ` values fails, e.g. a single term:

```python
func = Expression(-0.3 * (1 + Cos(Symbol("Phi"))))
amber_dihedral = AmberDihedral(func, Symbol("Phi"))
```
Perhaps negative `k` values (repulsive terms) are non-standard, although they seem to appear in the CHARMM parameter files (albeit extremely rarely).

I'll see if I can modify the `AmberDihedral` class to handle these terms.

**Comment by lohedges** [comment] 2018-02-14 12:52
Similarly, it's not possible to have a repulsive `AmberBond`, i.e. with a negative `k` value:

```python
# This is fine.
func = Expression(2 * (Symbol("R") - 0.5)**2.0)
amber_bond = AmberBond(func)

# This fails.
func = Expression(-2 * (Symbol("R") - 0.5)**2.0)
amber_bond = AmberBond(func)
```
Is this something that we want to support? Unlike the dihedral terms, I don't see any repulsive harmonic interactions the CHARMM parameter files, but I could imagine a situation in which they are used.

I'll continue fiddling with [amberparams.cpp](../blob/devel/corelib/src/libs/SireMM/amberparams.cpp) to see if I can get things to work.

**Comment by jmichel80** [comment] 2018-02-14 13:16
Hi Lester,

I think we should support correct algebraic expressions regardless of their
physical relevance. We normally don't have negative harmonic potentials as
these would lead to singularities but we should have the flexibility of
defining them, this could come handy in other contexts.

Best wishes,

Julien

--------------------------------------------------------------
Dr. Julien Michel,
Royal Society University Research Fellow
Room 263
School of Chemistry
University of Edinburgh
West Mains Road
Edinburgh, EH9 3JJ
United Kingdom
phone:   +44 (0)131 650 4797
http://www.julienmichel.net/
-------------------------------------------------------------

**Comment by lohedges** [comment] 2018-02-15 09:37
Thanks, Julien.

It looks like AMBER doesn't support negative cosine factors so pi should be added to the periodicity whenever this is the case. As such, the following should work fine, but currently fails:
 
```python
func = Expression(-0.3 * (1 + Cos(Symbol("Phi"))))
amber_dihedral = AmberDihedral(func, Symbol("Phi"))
```
Since CHARMM is happy with negative factors, I'm modifying the AmberDihedral class so that it can support both types, i.e. adding pi to the phase for AMBER, or returning a negative k value for CHARMM.

**Comment by lohedges** [comment] 2018-02-15 10:31
This is now fixed in the [feature-charmmff](/michellab/Sire/tree/feature-charmmff) branch. The issue will be closed when it is merged into [devel](/michellab/Sire/tree/devel).

`AmberDihedral` now takes an optional boolean argument to its constructor that specifies whether negative cosine terms are allowed. This argument is optional and its default value is `false` (AMBER style). This allows support for different dihedral representations, e.g.:

```python
from Sire.CAS import *
from Sire.MM import *

Phi = Symbol("Phi")

# Create a two-term dihedral expression with different signs.
func = Expression(0.3 * (1 + Cos(Phi)) - 0.7 * (1 + Cos(4 * Phi)))

# Create an AMBER style dihedral.
amber_dihedral = AmberDihedral(func, Phi)

# amber_dihedral.terms =
# <bound method terms of AmberDihedral( k[0] = 0.3, periodicity[0] = 1, phase[0] = 0, 
# k[1] = 0.7, periodicity[1] = 4, phase[1] = -3.14159 )>

# Create a CHARMM style dihedral.
amber_dihedral = AmberDihedral(func, Phi, True)

# amber_dihedral.terms =
# <bound method terms of AmberDihedral( k[0] = 0.3, periodicity[0] = 1, phase[0] = 0,
# k[1] = -0.7, periodicity[1] = 4, phase[1] = 0 )>
```

I'll add some additional tests to [test_amberparams.py](https://github.com/michellab/SireUnitTests/blob/master/unittests/SireIO/test_amberparams.py) to confirm that everything is working as expected.

(N.B. I could have created a new `CharmmDihedral` class, but it seems handy to re-use the existing code, and AmberDihedral should be able to handle negative terms anyway.)

Cheers.

**Comment by lohedges** [comment] 2018-02-15 14:39
Annoyingly, Sire can't tell that these two two trigonometric functions are the same:

```python
from Sire.CAS import *
from Sire.Maths import pi

Phi = Symbol("Phi")

f1 = Expression(-2 * Cos (Phi))
f2 = Expression(2 * Cos(Phi + pi))

# This fails.
assert f1 == f2
```
It would be nice if `Sire.CAS` could handle phase shifts when making comparisons.

For now, we can just assert that both expressions evaluate to the same result given the same input, i.e.:

```python
from pytest import approx

# Create a value object: Phi = 2.0.
val = Values(SymbolValue(Phi.ID(), 2.0)

# Make sure both expressions evaluate to the same result.
assert f1.evaluate(val) == approx(f2.evaluate(val))
```

**Comment by chryswoods** [comment] 2018-02-17 15:26
AmberDihedral does not support negative values of k because these are not supported in Amber. AmberDihedral is the intermediate class that sits between the Amber file formats and the SireCAS expressions. It has to evaluate to something that is supported by Amber, or else we would have to create yet another intermediary layer between "real Amber dihedrals" and AmberDihedral. You are right to re-use AmberDihedral as much as possible, although we must make sure that we don't break AmberDihedral's main purpose (i.e, always holding only valid Amber dihedral parameters).

You are right that the issue is because Amber uses a 180 degree phase instead of a negative k value. This is the same difference as seen when I was working with Gromacs Dihedrals. There is already code in AmberDihedral that detects this case and adds 180 degrees. See line 646 in amberparams.cpp, e.g.

```c++
                auto cos_term = child.base().asA<Cos>();
            
                //if the factor is negative, then we need to add pi to the periodicity
                //as amber does not have negative cos factors
                double factor = f.factor() * child.factor();

                if (factor < 0)
                {
                    factor *= -1;
                    cos_terms.append( factor * Cos( cos_term.argument() + SireMaths::pi ) );
                }
                else
                {
                    cos_terms.append( factor * cos_term );
                }
```

The above code was already in devel. Could you compare to what you have added and work out why the above code was buggy? Or how it differs to what you added?

Also, I agree that it is annoying that SireCAS cannot detect if two different expressions are really algebraically equivalent. There are two reasons for this deficiency:

(1) The two expressions are not equal because of numerical rounding. The different order of evaluation means that the expressions, though algebraically equal, are not numerically equal. If you look in the Amber and Gromacs tests you will see that I have added a Python function that randomly generates inputs to SireCAS expressions and reports them as equal if they give results that are equal within a numerical tolerance. This could be extended to a C++ function if you think it would help (e.g expression.isNumericallyEqual(other, nsamples=1000))

(2) Determining whether two different expressions are really algebraically equal is extremely difficult and requires a much more sophisticated CAS than SireCAS provides. You need to fully expand both expressions, order them using a consistent ordering and know about all of the major identities, e.g. cos(phi + 180) = -cos(phi). This was more effort than Sire needed, especially as Sire focusses on extremely rapid numeric evaluation.

**Comment by chryswoods** [comment] 2018-02-17 15:36
Indeed, now having looked at your code, I don't think your solution is right. AmberDihedral should never have negative k values. It also should "do the right thing" automatically when passed a SireCAS::Expression, i.e. the user should not have to pass an extra boolean flag to tell AmberDihedral whether or not to support negative k values (something AmberDihedral should never support as it is not supported by Amber). I would not merge in your changes to AmberDihedral as it breaks the contract with Amber.

A better solution would be to either derive a CharmmDihedral type that will detect whether there is a phase of 180, and then turn that into a negative k value, or to follow the same method that was used in GromacsDihedral (e.g. line 1583 in gromacsparams.cpp, function QList<GromacsDihedral> GromacsDihedral::construct(const Expression &dihedral, const Symbol &phi)). This tries to convert the dihedral to an AmberDihedral type, and then reads out the k, phase and periodicity parameters from the AmberDihedral. This means that all dihedrals we write to Gromacs files use positive k values and phases of 180 degrees, instead of 0 phases and negative k values. If the GromacsDihedral fails to create a valid AmberDihedral object, then an exception is raised and control is passed to a more complex expression parser (currently an "incomplete_code" saying that we only support Amber-style dihedrals at this point).

**Comment by chryswoods** [comment] 2018-02-17 16:32
I've given this some more thought. You are right that the issue is that AmberDihedral doesn't support negative k values as they negate the constant that is added to the dihedral (the "1" in the k[1 + cos(x)]) term). Gromacs has dihedrals that can be of the form k[ 1 - cos(x) ], which are really k[ 1 + cos(x+pi) ], so are valid Amber dihedrals (so can be converted to AmberDihedral).

However, Charmm allows a negative value of k, e.g. -k[ 1 + cos(x) ]. While before I was pretty sure that Amber doesn't allow negative k values, I wonder now whether I was wrong. Maybe we need to allow negative k values? This would mean we have to make the code more clever, as it must automatically detect the difference between -k[ 1 + cos(x) ] and k[ 1 - cos(x) ] (the latter should be converted to k[ 1 + cos(x+pi) ]).

We will know whether or not we are right because the "constant" term will sum up to the correct value (this is the part of the test that is currently failing). 

I suggest that you update your code to remove the boolean flag `has_neg_cos`, because AmberDihedral should be able to work everything out automatically, and should not rely on the user (or the code) providing extra information. A simple way to automate it would be to evaluate the dihedral once assuming that you can fix all negative cos terms by adding on a 180 degree phase, and then if that fails, skipping the phase and using a negative k value. I would be very surprised if there are any dihedrals that mix 180 phases with negative k values... ;-)

I also agree that you should add support for negative k values in AmberBond and AmberAngle, as it is worth adding this now then having errors later.

You will need to run the gromacs as well as the amber tests (or just all tests in SireIO to make sure that the change doesn't break gromacs parsing.

**Comment by lohedges** [comment] 2018-02-17 16:33
@chryswoods I totally agree with what you're saying. When used as it was before (with no additional argument to the constructor) the AmberDihedral class should only hold valid Amber dihedrals, since those are what are supported by Amber.

The point is that the existing code in devel fails to create an AmberDihedral if you pass in a cosine series with any negative k values. While the constructor adds a phase shift when detecting negative k, it doesn't correct for the swapped sign of k when comparing the sum of the constant terms, so gives an error. This is what I was seeing when I was attempting to represent certain CHARMM dihedrals using an AmberDihedral object. My changes should fix this problem, i.e. you always create a valid AmberDihedral (no negative k values) regardless of the signs in the cosine series expression that you pass in, which is what we want.

These changes shouldn't break anything in the existing code and I've re-run all the tests to check. The optional boolean flag just means that you can keep the negative k representation if desired, as I do with the CHARMM dihedrals (although it's probably fine to just use the phase shifted version). There are no other changes to the API.

As mentioned above, the code below now works, whereas in devel I get an error when creating a dihedral. Note that the AmberDihedral object is valid, i.e. k is always positive.

```python
from Sire.CAS import *
from Sire.MM import *

Phi = Symbol("Phi")

# Create a two-term dihedral expression with different signs.
func = Expression(0.3 * (1 + Cos(Phi)) - 0.7 * (1 + Cos(4 * Phi)))

# Create an AMBER style dihedral (with positive k values).
amber_dihedral = AmberDihedral(func, Phi)

# amber_dihedral.terms =
# <bound method terms of AmberDihedral( k[0] = 0.3, periodicity[0] = 1, phase[0] = 0, 
# k[1] = 0.7, periodicity[1] = 4, phase[1] = -3.14159 )>
```
Sorry if this wasn't clear.

Thanks for the info on making comparisons between Sire.CAS expressions. I assumed that this was something that was pretty tricky in general and beyond the scope of what's needed. After all, we're not writing Mathematica ;-)

Cheers.

**Comment by lohedges** [comment] 2018-02-17 16:48
Ah, I hadn't realised the alternative Gromacs form of  k[ 1 - cos(x) ]. As you say, this means that we'll need to be more clever in order to detect the difference. My changes don't currently catch this, although the Gromacs tests do pass.

I'll have another think :-)

**Comment by lohedges** [comment] 2018-02-20 11:51
According to [this](http://archive.ambermd.org/200808/0157.html) it seems that negative dihedral barrier heights should be okay. (There aren't any in the parm99.dat file, but AMBER should still handle them correctly if they are present.)

I've written some code that can detect between the different dihedral formats, k[ 1 + cos(x) ] and k[ 1 - cos(x) ], convert the latter into k[ 1 + cos(x + 180) ], and still support the presence of negative k values for the k[ 1 + cos(x) ] form. This works by checking whether the constant term is a sum of the factors, or a sum of their absolute values (or a mixture of), then phase shifting the appropriate terms (using the sign of the factor to work out which ones).

When I get a chance I'll write some more tests to make sure that everything is working as expected, then push the changes to the `feature-charmff` branch when I'm happy.

Cheers.

**Comment by chryswoods** [comment] 2018-02-20 12:00
Excellent. Please go ahead, and also do the same for negative k values for AmberBond and AmberAngle.

**Comment by lohedges** [comment] 2018-02-20 22:40
AmberBond and AmberAngle now support negative k values and AmberDihedral has support for all standard forms for dihedral terms: k [ 1 + cos(n phi - phase) ], k [ 1 - cos(n phi - phase) ], and -k [ 1 + cos(n phi - phase) ]. The only thing that isn't supported is -k [ 1 - cos(n phi - phase) ], which hopefully shouldn't occur in any force field.

Terms of the form k [ 1 - cos(n phi - phase) ] are converted to k [ 1 + cos(n phi - phase + 180) ] and negative k values are preserved for terms for which they are present. I've added some tests to [test_amberterms.py](https://github.com/michellab/SireUnitTests/blob/master/unittests/SireIO/test_amberterms.py) to check that functions generated from multiple terms with different forms are handled correctly.

**Comment by chryswoods** [comment] 2018-02-21 07:03
Excellent. Closing issue as you have done everything :-). Once you are happy with the tests submit a PR and I will merge into devel.

**Closed by chryswoods** 2018-02-21 07:03 UTC
Labels: bug

**Comment by lohedges** [comment] 2018-02-22 17:32
I'm happy with the tests, but still plan on developing within the `feature-charmmff` branch. (I need to add MMDetail for the CHARMM force-field, which might need some tweaking because of the different non-bonded 1-4 interactions and support for harmonic and cosine impropers.)

I don't mind waiting until it's complete before submitting a PR, or we could just merge the current changes. I'd then continue development work on `feature-charmmff` and submit another PR once it's finished.

Let me know what you'd prefer.

**Comment by chryswoods** [comment] 2018-02-25 13:47
Continue work and we will merge once I am back :-)
