### ISSUE TITLE
Sire fails assigning atom ids to fragments when parsing certain AMBER top files

### ISSUE THREAD

**Issue by ptosco** [michellab/Sire#217] opened 2018-08-06 11:11 UTC
`./corelib/src/libs/SireIO/amberprm.cpp` assumes that when a system is composed by multiple, separate molecules (e.g., disconnected fragments in a protein), these molecules can be described by a `start_idx` and a number of atoms. This is may not be a correct assumption, though, as a disulfide bond may join together two otherwise disconnected fragments which are non-consecutive in the atom sequence. So, while the code can indeed find the disconnected bits just fine, it fails when it comes to their description.
A good example is provided by the protein with PDB code `4S0V`, which consists of three disconnected fragments with the following intervals (1-based atom indices):

```
fragment 1:       1-1780
               2341-7069 (6509 indices overall)
fragment 2:    1781-2340 (560 indices overall)
fragment 3:    7070-7793 (724 indices overall)
```

However, due to the assumption described above, Sire thinks the intervals are consecutive, i.e.:

```
fragment 1:       1-6509 (6509 indices overall)
fragment 2:    6510-7069 (560 indices overall)
fragment 3:    7070-7793 (724 indices overall)
```

So it fails later on during the parsing thinking that there is a bond between disconnected molecules:

```
Failed to parse 'input_tLeap.top' with parser 'PRM7'", "Something went wrong as there is a bond between two different molecules!
```

However, no such bond exists, and the error message is a consequence of the incorrect partitioning of atom indices among fragments.
A possible solution could be to refactor `./corelib/src/libs/SireIO/amberprm.cpp` to pass a `QMap` mapping atom indices to fragment indices rather than passing a `start_idx` and a number of atoms.

**Comment by chryswoods** [comment] 2018-08-08 14:07
Hi Paolo :-). Thanks for your detailed bug report and for your useful suggestion. Yes, I agree that the best way for us to fix this is to use a QMap or QHash as you suggest. We'll get on this soon

**Comment by chryswoods** [comment] 2019-01-31 16:14
I'm closing this as the tests on the newest code show that the issue is resolved in the new AmberPrm. You can download and test the binary on your files from here 
http://siremol.org/largefiles/sire_releases/download.php?name=sire_devel_latest_linux.run. If it is still an issue, please reopen and supply problematic input files :-)

**Closed by chryswoods** 2019-01-31 16:14 UTC
