### ISSUE TITLE
sire 2015.0 only supports the Reference platform of OpenMM on ubuntu 14.04.3

### ISSUE THREAD

**Issue by jmichel80** [michellab/Sire#79] opened 2015-11-29 20:21 UTC
Update on #64 
It turns out that I was not getting the CUDA platform to work because I was using cuda-7.5. 
I have now installed recent CUDA drivers that support the GTX980 TI cards, and then cuda-7.0. 

I had to copy /home/julien/local/cuda-7.0/lib64/libcufft.so.7.0 to /home/julien/sire.app/lib otherwise I had a missing library for /home/julien/sire.app/lib/plugins/libOpenMMCUDA.so

OpenMM seems to be correctly installed within sire python
[ julien@mechagodzilla: ~/sire.app/lib/python3.4/site-packages/simtk ]$ pwd
/home/julien/sire.app/lib/python3.4/site-packages/simtk
[ julien@mechagodzilla: ~/sire.app/lib/python3.4/site-packages/simtk ]$ ~/sire.app/bin/python testInstallation.py 
There are 4 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
3 CUDA - Successfully computed forces
4 OpenCL - Successfully computed forces

Median difference in forces between platforms:

Reference vs. CPU: 1.97804e-05
Reference vs. CUDA: 2.15381e-05
CPU vs. CUDA: 1.55518e-05
Reference vs. OpenCL: 2.15343e-05
CPU vs. OpenCL: 1.55498e-05
CUDA vs. OpenCL: 1.17736e-07

I confirm that somd-freenrg crashes because OpenMM raises a RunTimeError (RuntimeError: There is no registered Platform called "CUDA"). 
This occurs in the subroutine SireMove::OpenMMFrEnergySt::createContext  on line 2800

        OpenMM::Platform& platform_openmm = OpenMM::Platform::getPlatformByName(platform_type.toStdString());

So when calling OpenMM from C++, it appears that all the platforms available by plugins are not detected. But they are all detected when calling OpenMM from Python. 

Weird....

**Comment by jmichel80** [comment] 2015-11-30 11:52
Good news. It is simply a matter of exporting the environment variable OPENMM_PLUGIN_DIR before calling somd-freenrg

export OPENMM_PLUGIN_DIR=/home/julien/sire.app/lib/plugins/

I wish it didn't take me hours to realise this was the problem !

**Comment by ppxasjsm** [comment] 2015-11-30 12:01
Ah! Yes I could have probably told you that. I take it the issue is now closed?

**Comment by ppxasjsm** [comment] 2015-12-10 17:02
So on Lisa's workstation I observe something I have encountered before and is probably worth documenting somewhere, so here is as good as any place I guess. 
```
~/sire.app/lib/python3.4/site-packages/simtk$ ~/sire.app/bin/python testInstallation.py 
There are 4 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
3 CUDA - Error computing forces with CUDA platform
4 OpenCL - Error computing forces with OpenCL platform

OpenCL platform error: Error initializing context: clGetPlatformIDs (-1001)

CUDA platform error: Error initializing CUDA: CUDA_ERROR_UNKNOWN (999) at /anaconda/conda-bld/work/openmm-6.3/platforms/cuda/src/CudaContext.cpp:92

Median difference in forces between platforms:

Reference vs. CPU: 1.97908e-05
```

This can be fixed by running ./deviceQuery in NVIDIA_Samples as a root user. 
@jmichel80 do you have a symbolic link to your nvcc compiler at /usr/local/cuda/bin/ ?
It seems that without it, I get error  when testing OpenMM installation: 

```
~/sire.app/lib/python3.4/site-packages/simtk$ ~/sire.app/bin/python testInstallation.py 
There are 4 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
3 CUDA - Error computing forces with CUDA platform
4 OpenCL - Successfully computed forces

CUDA platform error: Error launching CUDA compiler: 32512
sh: 1: /usr/local/cuda/bin/nvcc: not found

```
despite having nvcc in my PATH.

**Comment by ppxasjsm** [comment] 2015-12-10 17:06
Ok found a fix:
```
export OPENMM_CUDA_COMPILER=/usr/local/cuda-7.0/bin/nvcc
```

**Closed** 2015-12-10 17:14 UTC
