### ISSUE TITLE
installing from binary

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/Sire#169] opened 2017-11-07 14:57 UTC
I have observed very strange behaviour installing and running test from the latest 17.2 binary. 

The user used for installing somehow changed user and group id from 1000 to 500, while running sire tests. 
```
drwx------   9  500  500  4096 Nov  7 12:53 manager
```
Look at timestamp of installation:

```
-rw-rw-r--  1 root root  3699 Feb  4  2016 LICENSE.txt
drwxrwxr-x  2 root root  4096 Aug 31 15:38 envs
drwxrwxr-x  3 root root  4096 Aug 31 15:38 ssl
drwxrwxr-x  3 root root  4096 Aug 31 15:38 etc
drwxrwxr-x  5 root root  4096 Aug 31 15:38 share
drwxrwxr-x  3 root root  4096 Aug 31 15:38 docs
drwxrwxr-x  2 root root  4096 Aug 31 15:38 licenses
drwxrwxr-x 11 root root  4096 Aug 31 15:39 include
drwxrwxr-x 10 root root 12288 Nov  7 12:44 lib
drwxrwxr-x 59 root root  4096 Nov  7 12:53 pkgs
drwxrwxr-x  2 root root  4096 Nov  7 12:53 bin
drwxrwxr-x  2 root root  4096 Nov  7 12:53 conda-meta
```

And there appear to be some other errors:
```
Package plan for installation in environment /home/common/sire.app_17.2.0:

The following NEW packages will be INSTALLED:

    pycurl: 7.43.0-py35_0

The following packages will be UPDATED:

    conda:  4.3.25-py35_0 --> 4.3.30-py35hf9359ed_0

pycurl-7.43.0- 100% |################################################################| Time: 0:00:00   6.87 MB/s
conda-4.3.30-p 100% |################################################################| Time: 0:00:00  13.85 MB/s

bzip2: Compressed file ends unexpectedly;
	perhaps it is corrupted?  *Possible* reason follows.
bzip2: Inappropriate ioctl for device
	Input file = (stdin), output file = (stdout)

It is possible that the compressed file(s) have become corrupted.
You can use the -tvv option to test integrity of such files.

You can use the `bzip2recover' program to attempt to recover
data from undamaged sections of corrupted files.

tar: Child returned status 2
tar: Error is not recoverable: exiting now
Could not find SireUnitTests/README.md in download - everything ok?
You should find the unit tests in /users/common/sire.app_17.2.0/pkgs/sire-2017.2.0/share/Sire/test/SireUnitTests/unittests

Running C++ unit tests...

```

**Comment by chryswoods** [comment] 2017-11-08 12:01
Strange - thanks for raising this. I suspect it is caused by the code I added to try to trim down the size of the package because of all of the intel mkl cruft. I'll take a look at this...

**Comment by chryswoods** [comment] 2018-01-09 11:46
Closing as the 17.2 release was aborted. I hope this issue does not resurface in the 2017.3.0 release (I have not seen it on my test machines - please check the md5sum against that on the website when you download to rule out file corruption issues)

**Closed by chryswoods** 2018-01-09 11:46 UTC
